version: "3.5"

services:
  php74:
    container_name: php
    image: moonoise/php74_pdo_oci
    #restart: always
    networks:
      - network_1
    ports:
      - "8098:80"
    volumes:
      - ./www:/var/www/html/

  Mariadb_1:
    container_name: mariadb
    image: mariadb
    #restart: always
    networks:
      - network_1
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: "myuser"
      MYSQL_PASSWORD: "mypassword"
    volumes:
      - ./database:/var/lib/mysql

  phpmyadmin_1:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - Mariadb_1
    environment:
      - PMA_ARBITRARY=1
      - TESTSUITE_PASSWORD=root
      - PMA_PORT=3309
      - UPLOAD_LIMIT= 3000000000
    #restart: always
    ports:
      - "8097:80"
    networks:
      - network_1
    volumes:
      - /sessions

networks:
  network_1:
